library(haven)
library(dplyr)
library(tidyverse)
library(here)
dir.create("data")
dir.create("data_output")
dir.create("scripts")

#download files
download.file("http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2021-03-04/data/calendar.csv.gz","data/Amsterdam_calendar.csv.gz")
download.file("http://data.insideairbnb.com/france/ile-de-france/paris/2021-03-04/data/calendar.csv.gz","data/Paris_calendar.csv.gz")
download.file("http://data.insideairbnb.com/united-kingdom/england/london/2021-03-05/data/calendar.csv.gz","data/London_calendar.csv.gz")
download.file("http://data.insideairbnb.com/ireland/leinster/dublin/2021-03-07/data/calendar.csv.gz","data/Dublin_calendar.csv.gz")
download.file("http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2021-03-07/data/calendar.csv.gz","data/Madrid_calendar.csv.gz")
download.file("http://data.insideairbnb.com/italy/lazio/rome/2021-03-07/data/calendar.csv.gz","data/Rome_calendar.csv.gz")
download.file("http://data.insideairbnb.com/austria/vienna/vienna/2021-03-07/data/calendar.csv.gz","data/Vienna_calendar.csv.gz")
download.file("http://data.insideairbnb.com/portugal/lisbon/lisbon/2021-03-08/data/calendar.csv.gz","data/Lisbon_calendar.csv.gz")
download.file("http://data.insideairbnb.com/germany/be/berlin/2021-03-12/data/calendar.csv.gz","data/Berlin_calendar.csv.gz")
download.file("http://data.insideairbnb.com/czech-republic/prague/prague/2021-03-13/data/calendar.csv.gz","data/Prague_calendar.csv.gz")
download.file("http://data.insideairbnb.com/belgium/bru/brussels/2021-03-17/data/calendar.csv.gz","data/Brussels_calendar.csv.gz")
download.file("http://data.insideairbnb.com/greece/attica/athens/2021-03-20/data/calendar.csv.gz","data/Athens_calendar.csv.gz")
download.file("http://data.insideairbnb.com/belgium/vlg/antwerp/2021-03-26/data/calendar.csv.gz","data/Antwerp_calendar.csv.gz")
download.file("http://data.insideairbnb.com/denmark/hovedstaden/copenhagen/2021-03-27/data/calendar.csv.gz","data/Copenhagen_calendar.csv.gz")
download.file("http://data.insideairbnb.com/norway/oslo/oslo/2021-03-27/data/calendar.csv.gz","data/Oslo_calendar.csv.gz")
download.file("http://data.insideairbnb.com/sweden/stockholms-l%C3%A4n/stockholm/2021-03-27/data/calendar.csv.gz","data/Stockholm_calendar.csv.gz")
download.file("http://data.insideairbnb.com/latvia/riga/riga/2021-03-29/data/calendar.csv.gz","data/Riga_calendar.csv.gz")

#Couple files to variables
Amsterdam<-read.csv("data/Amsterdam_calendar.csv.gz")
Paris<-read.csv("data/Paris_calendar.csv.gz")
London<-read.csv("data/London_calendar.csv.gz")
Dublin<-read.csv("data/Dublin_calendar.csv.gz")
Madrid<-read.csv("data/Madrid_calendar.csv.gz")
Rome<-read.csv("data/Rome_calendar.csv.gz")
Vienna<-read.csv("data/Vienna_calendar.csv.gz")
Lisbon<-read.csv("data/Lisbon_calendar.csv.gz")
Berlin<-read.csv("data/Berlin_calendar.csv.gz")
Prague<-read.csv("data/Prague_calendar.csv.gz")
Brussels<-read.csv("data/Brussels_calendar.csv.gz")
Athens<-read.csv("data/Athens_calendar.csv.gz")
Antwerp<-read.csv("data/Antwerp_calendar.csv.gz")
Copenhagen<-read.csv("data/Copenhagen_calendar.csv.gz")
Oslo<-read.csv("data/Oslo_calendar.csv.gz")
Stockholm<-read.csv("data/Stockholm_calendar.csv.gz")
Riga<-read.csv("data/Riga_calendar.csv.gz")

#Convert $date characters to date variables
Amsterdam$date<-as.Date(Amsterdam$date)
Paris$date<-as.Date(Paris$date)
London$date<-as.Date(London$date)
Dublin$date<-as.Date(Dublin$date)
Madrid$date<-as.Date(Madrid$date)
Rome$date<-as.Date(Rome$date)
Vienna$date<-as.Date(Vienna$date)
Lisbon$date<-as.Date(Lisbon$date)
Berlin$date<-as.Date(Berlin$date)
Prague$date<-as.Date(Prague$date)
Brussels$date<-as.Date(Brussels$date)
Athens$date<-as.Date(Athens$date)
Antwerp$date<-as.Date(Antwerp$date)
Copenhagen$date<-as.Date(Copenhagen$date)
Oslo$date<-as.Date(Oslo$date)
Stockholm$date<-as.Date(Stockholm$date)
Riga$date<-as.Date(Riga$date)

#checking earliest date in data files
min(Amsterdam$date)
min(Paris$date)
min(London$date)
min(Dublin$date)
min(Madrid$date)
min(Rome$date)
min(Vienna$date)
min(Lisbon$date)
min(Berlin$date)
min(Prague$date)
min(Brussels$date)
min(Athens$date)
min(Antwerp$date)
min(Copenhagen$date)
min(Oslo$date)
min(Stockholm$date)
min(Riga$date)

#checking for latest date in data files
max(Amsterdam$date)
max(Paris$date)
max(London$date)
max(Dublin$date)
max(Madrid$date)
max(Rome$date)
max(Vienna$date)
max(Lisbon$date)
max(Berlin$date)
max(Prague$date)
max(Brussels$date)
max(Athens$date)
max(Antwerp$date)
max(Copenhagen$date)
max(Oslo$date)
max(Stockholm$date)
max(Riga$date)

download.file("http://data.insideairbnb.com/latvia/riga/riga/2021-03-29/data/calendar.csv.gz","data/Riga_calendar.csv.gz")
Riga<-read.csv("data/Riga_calendar.csv.gz")


Riga<-Riga %>% 
  group_by(date) %>% 
  mutate(avg_price = mean(parse_number(price))) %>% 
  distinct(date, avg_price, .keep_all = T)
View(Riga)
